name: '[QE] Maintenance'

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * SUN'

jobs:
  clean:
    name: Clean dirty workspaces
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: 'Deploy VTEX Toolbelt'
        uses: vtex/action-toolbelt@v4
        with:
          account: productusqa
          appKey: ${{ secrets.VTEX_TOOLBELT_KEY }}
          appToken: ${{ secrets.VTEX_TOOLBELT_TOKEN }}

      - name: Clean dirty workspaces
        run: |
          DIRTY=$(vtex workspace ls | grep -E [[:digit:]]{7} | awk '{print $1}' | xargs)
          [[ -n $DIRTY ]] && vtex workspace delete $DIRTY || echo "Ohay, Nothing to clean!"

      - name: Logout
        run: |
          vtex logout

