name: '[Lint] Quality Engineering'

on:
  # Allow this to be called by others
  workflow_call:

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Install packages'
        run: |
          PWD=$(pwd)
          for DIR in ['.', './node', './react']; do
            if [[ -f "$DIR/package.json" ]]; then
              echo "Installing $DIR packages..."
              cd $DIR 
              yarn install --frozen-lockfile
              cd $PWD
            fi
      - name: 'Run lint'
        run: yarn lint
