name: '[Lint] Quality Engineering'

on:
  # Allow this to be called by others
  workflow_call:

env:
  LOOP_YARN: |
    PWD=$(pwd)
    if [[ -f "package.json" ]]; then
      echo "Install root packages"
      yarn install --frozen-lockfile
    fi
    if [[ -f "./node/package.json" ]]; then
      echo "Install node packages"
      cd ./node && yarn install --frozen-lockfile
      cd $PWD
    fi
    if [[ -f "./react/package.json" ]]; then
      echo "Install react packages"
      cd ./react && yarn install --frozen-lockfile
      cd $PWD
    fi

jobs:
  lint:
    name: 'QE'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Install packages'
        run: echo $LOOP_YARN | bash -
      - name: 'Run lint'
        run: yarn lint
