name: '[QE] Quality Engineering'

on:
  # Just to make easier debug typos
  workflow_dispatch:
jobs:
  safeCheck:
    name: 'Security check'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Deploy VTEX Toolbelt'
        uses: vtex/action-toolbelt@v2
        with:
          account: productusqa
          appKey: ${{ secrets.VTEX_TOOLBELT_KEY }}
          appToken: ${{ secrets.VTEX_TOOLBELT_TOKEN }}

      - name: 'Do something else as logged user'
        run: vtex-e2e workspace ls

      - name: 'Do a logout'
        run: vtex-e2e logout
