name: '[QE] Quality Engineering'

on:
  # Just to make easier debug typos
  workflow_dispatch:
jobs:
  safeCheck:
    name: 'Security check'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: 'Test beta version of workflow'
        uses: vtex/action-toolbelt@main
        with:
            account: productusqa
            appKey: ${{ secrets.VTEX_TOOLBELT_KEY }}
            appToken: ${{ secrets.VTEX_TOOLBELT_TOKEN }}
            workspace: master
            bin: vtex-e2e
            git: vtex/toolbelt
            branch: qe/cypress
