name: '[QE] Quality Engineering'

on:
  # Just to make easier debug typos
  workflow_dispatch:
jobs:
  safeCheck:
    name: 'Security check'
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: 'Test beta version of workflow'
        uses: vtex/action-toolbelt@main
        with:
            account: Account test
            appKey: 123456
            appToken: 321654
            workspace: master
            branch: qe/cypress
