name: '[QE] Quality Engineering'

on:
  # Just to make easier debug typos
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        type: boolean
        required: false
        default: false
  # Allow this to be called by others
  workflow_call:
    inputs:
      # -----------------------------------------------------------------------------------------
      # Danger Section
      # -----------------------------------------------------------------------------------------
      danger:
        description: 'Run node Danger action?'
        type: boolean
        default: false
        required: false
      dangerRequireChanglog:
        description: 'Require changlog version for Danger?'
        type: boolean
        default: false
        required: false
      # -----------------------------------------------------------------------------------------
      # Node JS Section [Lint, Tests, Sonar]
      # -----------------------------------------------------------------------------------------
      nodeLint:
        description: 'Run node lint?'
        type: boolean
        default: false
        required: false
      # Unit tests for NodeJS
      nodeTest:
        description: 'Run node unit tests?'
        type: boolean
        default: false
        required: false
      nodeTestCmd:
        description: 'What is the JS command to run unit tests?'
        type: string
        default: yarn test --coverage
        required: false
      nodeSonar:
        description: 'Run node SonarCloud?'
        type: boolean
        default: false
        required: false
      nodeSonarProjectKey:
        description: 'What is the SonarCloud project for Node?'
        type: string
        default: none
        required: false
      nodeSonarOrganization:
        description: 'What is the SonarCloud Organization for Node?'
        type: string
        default: none
        required: false
      # -----------------------------------------------------------------------------------------
      # dotNet Section [Sonar]
      # -----------------------------------------------------------------------------------------
      dotnetSonar:
        description: 'Run SonarCloud for dotNet?'
        type: boolean
        default: false
        required: false
      dotnetSonarProjectKey:
        description: 'What is the SonarCloud project for dotnet?'
        type: string
        default: none
        required: false
      dotnetSonarOrganization:
        description: 'What is the SonarCloud Organization for dotnet?'
        type: string
        default: none
        required: false
      # -----------------------------------------------------------------------------------------
      # Cypress section
      # -----------------------------------------------------------------------------------------
      cypress:
        description: 'Do E2E tests?'
        type: boolean
        default: false
        required: false
    secrets:
      # -----------------------------------------------------------------------------------------
      # Secretes for GitHub token, SonarCloud token and Cypress JSON
      # -----------------------------------------------------------------------------------------
      githubToken:
        description: 'A token to access GitHub staff'
        required: false
      sonarToken:
        description: 'A token to have access to SonarCloud'
        required: false
      cypressJson:
        description: 'A JSON to pass make Cy-Runner works'
        required: false

jobs:
  # check here if it is safe to run it on pull_request_target events
  safeCheck:
    name: 'Security check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Stop if from out side without the label "safe to test"'
        if: >-
          ( github.event.pull_request.head.repo.fork == true ) &&
          ( !contains(github.event.pull_request.labels.*.name, 'safe to test') )
        run: |
          echo "Attention:"
          echo " "
          echo "💡 Thank you for submitting your contribution on this repository!"
          echo "   Before merge this PR, it must pass our Quality Engineering process."
          echo "   Please, ask for someone from VTEX to read your changes and add the label 'safe to test' on your PR."
          echo " "
          echo "   If you made changes after the approval, someone needs redo the label thing."
          exit 1
      - name: 'Remove the label "safe to test" to avoid run again on changed code'
        if: ( contains(github.event.pull_request.labels.*.name, 'safe to test') )
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: safe to test
          GITHUB_TOKEN: ${{ secrets.githubToken }}
      - name: 'Create a file'
        run: sudo touch /mnt/charles
      - name: Debug
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        timeout-minutes: 5
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

  danger:
    name: 'Danger'
    if: ${{ inputs.danger }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [safeCheck]
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Danger CI'
        uses: vtex/danger@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          REQUIRE_CHANGELOG_VERSION: ${{ inputs.dangerRequireChanglog }}

  nodeLint:
    name: 'Lint / node'
    if: ${{ inputs.nodeLint }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [safeCheck]
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Install packages'
        run: |
          PWD=$(pwd)
          for DIR in '.' 'node' 'react'; do
            if [[ -f "$DIR/package.json" ]]; then
              echo "Installing $DIR packages..."
              cd "$PWD/$DIR"
              yarn install --frozen-lockfile
            fi
          done
      - name: 'Run lint'
        run: yarn lint

  nodeTest:
    name: 'Unit tests / node'
    if: ${{ inputs.nodeTest }}
    runs-on: ubuntu-latest
    needs: [nodeLint]
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Run test on every builder directory'
        uses: vtex/action-io-app-test@master

  nodeSonar:
    name: 'Sonar / node'
    if: ( inputs.nodeSonar ) && ( github.actor != 'dependabot[bot]' )
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [nodeLint]
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
        with:
          fetch-depth: 0
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Install packages'
        run: |
          PWD=$(pwd)
          for DIR in '.' 'node' 'react'; do
            if [[ -f "$DIR/package.json" ]]; then
              echo "Installing $DIR packages..."
              cd "$PWD/$DIR"
              yarn install --frozen-lockfile
            fi
          done
      - name: 'Trusted SonarCloud Scan'
        if: ( github.event.pull_request.head.repo.fork == false )
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          SONAR_TOKEN: ${{ secrets.sonarToken }}
      - name: 'Untrusted SonarCloud Scan'
        if: ( github.event.pull_request.head.repo.fork == true )
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          SONAR_TOKEN: ${{ secrets.sonarToken }}
        with:
          # SonarCloud doesn't treat pull_request_target, so we need this
          args: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} 
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}

  dotnetSonar:
    name: 'Sonar / dotnet'
    if: ( inputs.dotnetSonar ) && ( github.actor != 'dependabot[bot]' )
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [safeCheck]
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
        with:
          fetch-depth: 0
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: 'Not ready yet'
        run: echo 1

  cypress:
    name: 'Cypress'
    if: ( inputs.cypress ) && ( github.event.pull_request.draft == false )
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [safeCheck]
    concurrency:
      group: ${{ github.workflow }}
    steps:
      - name: 'Trusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == false )
      - name: 'Untrusted checkout'
        uses: actions/checkout@v3
        if: ( github.event.pull_request.head.repo.fork == true )
      - name: 'Checkout Cy-Runner'
        uses: actions/checkout@v3
        with:
          repository: vtex-apps/cy-runner
          ref: main
          path: cy-runner
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: 'Install packages'
        run: |
          PWD=$(pwd)
          for DIR in '.' 'node' 'react'; do
            if [[ -f "$DIR/package.json" ]]; then
              echo "Installing $DIR packages..."
              cd "$PWD/$DIR"
              yarn install --frozen-lockfile
            fi
          done
      - name: 'Install Cy-Runner'
        run: |
          yarn install --frozen-lockfile 
          rm -rf .git
          yarn cypress info
        working-directory: cy-runner
      - name: 'Run Cy-Runner'
        run: yarn cy-r
        env:
          VTEX_QE: ${{ secrets.cypressJSON }}
          NODE_NO_WARNINGS: 1
      - name: Save results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cy-runner-logs
          path: |
            cy-runner/logs
            !cy-runner/logs/**/*.mp4
          retention-days: 3
