name: '[Security] Quality Engineering'

on:
  # Allow this to be called by others
  workflow_call:

jobs:
  # check here if it is safe to run it on pull_request_target events
  safe:
    name: 'Security check'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Stop if from out side without the label "safe to test"'
        if: >-
          ( github.event.pull_request.head.repo.fork == true ) &&
          ( !contains(github.event.pull_request.labels.*.name, 'safe to test') )
        run: |
          echo "Attention:"
          echo "   "
          echo "💡 Thank you for submitting your contribution on this repository!"
          echo "   Before merge this PR, it must pass our Quality Engineering process."
          echo "   Please, ask for someone from VTEX to read your changes and add the label 'safe to test' on your PR."
          echo "   "
          echo "   If you made changes after the approval, someone needs redo the label thing."
          exit 1
